backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "tags", name: "tags", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Hero Image", name: "heroimg", widget: "image"}
      - {label: "Hero Image Height", name: "heroheight", widget: "number"}
      - {label: "Feature Text", name: "featuretext", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "base"}
      - {label: "tags", name: "tags", widget: "hidden", default: "about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Hero Image", name: "heroimg", widget: "image"}
      - {label: "Hero Image Height", name: "heroheight", widget: "number"}
      - {label: "Feature Text", name: "featuretext", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
